### PR TITLE
BitcoinCash validator

### PR DESCRIPTION
**Pull request by Paulsky**
Added a standalone BCH validator. Please see this issue; #40 

I used https://github.com/simpleledger/bchaddrjs instead of https://github.com/bitcoincashjs/bchaddrjs because that fork supports SPL address validation.

### CODE REVIEW

**Comment by Paulsky** [comment]
Hmm, not sure what I did wrong. I just made one commit (not 19) on a new branch of my fork....?

**Comment by GusGold** [comment]
Might have forked master, and then PRed in to dev. No worries though :)

**Comment by Paulsky** [comment]
@GusGold any update on this? :)

**Comment by GusGold** [comment]
Fixed #40

**Comment by GusGold** [comment]
Thanks for the reminder on this one @Paulsky Will be updated on NPM shortly

**Comment by Paulsky** [comment]
Thank you very much @GusGold 🙏

**Pull request merged**
